/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockokxrouterSol from "./Mockokxrouter.sol";
export type { mockokxrouterSol };
export type { MockERC20 } from "./MockERC20";
