/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockOKXRouter,
  MockOKXRouterInterface,
} from "../../../../contracts/mocks/Mockokxrouter.sol/MockOKXRouter";

const _abi = [
  {
    inputs: [],
    name: "leaveAllowanceUnspent",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fa806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633fac93b01461003b5780638a0ccd561461003d575b600080fd5b005b61003b61004b366004610157565b6040516323b872dd60e01b8152336004820152306024820152604481018490526001600160a01b038516906323b872dd906064016020604051808303816000875af115801561009e573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100c2919061019b565b5060405163a9059cbb60e01b8152336004820152602481018290526001600160a01b0383169063a9059cbb906044016020604051808303816000875af1158015610110573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610134919061019b565b5050505050565b80356001600160a01b038116811461015257600080fd5b919050565b6000806000806080858703121561016d57600080fd5b6101768561013b565b93506020850135925061018b6040860161013b565b9396929550929360600135925050565b6000602082840312156101ad57600080fd5b815180151581146101bd57600080fd5b939250505056fea2646970667358221220ce6702a48bc9eded098a1f2b8e1ce82ff9900a93e92c7b1b3979b828514d58bd64736f6c63430008180033";

type MockOKXRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockOKXRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockOKXRouter__factory extends ContractFactory {
  constructor(...args: MockOKXRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockOKXRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockOKXRouter__factory {
    return super.connect(runner) as MockOKXRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockOKXRouterInterface {
    return new Interface(_abi) as MockOKXRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockOKXRouter {
    return new Contract(address, _abi, runner) as unknown as MockOKXRouter;
  }
}
