/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockOKXRouter,
  MockOKXRouterInterface,
} from "../../../../contracts/mocks/Mockokxrouter.sol/MockOKXRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101f4806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638a0ccd5614610030575b600080fd5b61004361003e366004610151565b610045565b005b6040516323b872dd60e01b8152336004820152306024820152604481018490526001600160a01b038516906323b872dd906064016020604051808303816000875af1158015610098573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100bc9190610195565b5060405163a9059cbb60e01b8152336004820152602481018290526001600160a01b0383169063a9059cbb906044016020604051808303816000875af115801561010a573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061012e9190610195565b5050505050565b80356001600160a01b038116811461014c57600080fd5b919050565b6000806000806080858703121561016757600080fd5b61017085610135565b93506020850135925061018560408601610135565b9396929550929360600135925050565b6000602082840312156101a757600080fd5b815180151581146101b757600080fd5b939250505056fea2646970667358221220746642f18e1a4bda89376b6d76232a79dc875b0a3bd8b7a558a14ed83fb4acf364736f6c63430008180033";

type MockOKXRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockOKXRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockOKXRouter__factory extends ContractFactory {
  constructor(...args: MockOKXRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockOKXRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockOKXRouter__factory {
    return super.connect(runner) as MockOKXRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockOKXRouterInterface {
    return new Interface(_abi) as MockOKXRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockOKXRouter {
    return new Contract(address, _abi, runner) as unknown as MockOKXRouter;
  }
}
