/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Vault {
  export type SwapInstructionStruct = {
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    expectedAmountOut: BigNumberish;
    minAmountOut: BigNumberish;
    targetAllocationBps: BigNumberish;
    swapCalldata: BytesLike;
  };

  export type SwapInstructionStructOutput = [
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    expectedAmountOut: bigint,
    minAmountOut: bigint,
    targetAllocationBps: bigint,
    swapCalldata: string
  ] & {
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    expectedAmountOut: bigint;
    minAmountOut: bigint;
    targetAllocationBps: bigint;
    swapCalldata: string;
  };
}

export interface VaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedAssets"
      | "deposit"
      | "executeRebalance"
      | "executor"
      | "getAllowedAssets"
      | "initialize"
      | "isAllowedAsset"
      | "lastRebalanceTimestamp"
      | "maxAllocationBps"
      | "maxSlippageBps"
      | "minRebalanceInterval"
      | "okxRouter"
      | "owner"
      | "updateOkxRouter"
      | "updateRiskParams"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "OkxRouterUpdated"
      | "RebalanceExecuted"
      | "RiskParamsUpdated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedAssets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRebalance",
    values: [Vault.SwapInstructionStruct[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "executor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllowedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRebalanceTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxAllocationBps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxSlippageBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minRebalanceInterval",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "okxRouter", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateOkxRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskParams",
    values: [BigNumberish[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllowedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRebalanceTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAllocationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxSlippageBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minRebalanceInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "okxRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateOkxRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OkxRouterUpdatedEvent {
  export type InputTuple = [
    previousRouter: AddressLike,
    newRouter: AddressLike
  ];
  export type OutputTuple = [previousRouter: string, newRouter: string];
  export interface OutputObject {
    previousRouter: string;
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceExecutedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    reasoningId: BytesLike,
    tokensIn: AddressLike[],
    tokensOut: AddressLike[],
    amountsIn: BigNumberish[],
    amountsOut: BigNumberish[]
  ];
  export type OutputTuple = [
    timestamp: bigint,
    reasoningId: string,
    tokensIn: string[],
    tokensOut: string[],
    amountsIn: bigint[],
    amountsOut: bigint[]
  ];
  export interface OutputObject {
    timestamp: bigint;
    reasoningId: string;
    tokensIn: string[];
    tokensOut: string[];
    amountsIn: bigint[];
    amountsOut: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskParamsUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vault extends BaseContract {
  connect(runner?: ContractRunner | null): Vault;
  waitForDeployment(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedAssets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeRebalance: TypedContractMethod<
    [instructions: Vault.SwapInstructionStruct[], reasoningId: BytesLike],
    [void],
    "nonpayable"
  >;

  executor: TypedContractMethod<[], [string], "view">;

  getAllowedAssets: TypedContractMethod<[], [string[]], "view">;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      executor_: AddressLike,
      okxRouter_: AddressLike,
      allowedAssets_: AddressLike[],
      maxAllocationBps_: BigNumberish[],
      maxSlippageBps_: BigNumberish,
      minRebalanceInterval_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isAllowedAsset: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastRebalanceTimestamp: TypedContractMethod<[], [bigint], "view">;

  maxAllocationBps: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxSlippageBps: TypedContractMethod<[], [bigint], "view">;

  minRebalanceInterval: TypedContractMethod<[], [bigint], "view">;

  okxRouter: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  updateOkxRouter: TypedContractMethod<
    [newRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRiskParams: TypedContractMethod<
    [
      newMaxAllocationBps: BigNumberish[],
      newMaxSlippageBps: BigNumberish,
      newMinRebalanceInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedAssets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeRebalance"
  ): TypedContractMethod<
    [instructions: Vault.SwapInstructionStruct[], reasoningId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllowedAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      executor_: AddressLike,
      okxRouter_: AddressLike,
      allowedAssets_: AddressLike[],
      maxAllocationBps_: BigNumberish[],
      maxSlippageBps_: BigNumberish,
      minRebalanceInterval_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAllowedAsset"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastRebalanceTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxAllocationBps"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxSlippageBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minRebalanceInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "okxRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateOkxRouter"
  ): TypedContractMethod<[newRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskParams"
  ): TypedContractMethod<
    [
      newMaxAllocationBps: BigNumberish[],
      newMaxSlippageBps: BigNumberish,
      newMinRebalanceInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OkxRouterUpdated"
  ): TypedContractEvent<
    OkxRouterUpdatedEvent.InputTuple,
    OkxRouterUpdatedEvent.OutputTuple,
    OkxRouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceExecuted"
  ): TypedContractEvent<
    RebalanceExecutedEvent.InputTuple,
    RebalanceExecutedEvent.OutputTuple,
    RebalanceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RiskParamsUpdated"
  ): TypedContractEvent<
    RiskParamsUpdatedEvent.InputTuple,
    RiskParamsUpdatedEvent.OutputTuple,
    RiskParamsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OkxRouterUpdated(address,address)": TypedContractEvent<
      OkxRouterUpdatedEvent.InputTuple,
      OkxRouterUpdatedEvent.OutputTuple,
      OkxRouterUpdatedEvent.OutputObject
    >;
    OkxRouterUpdated: TypedContractEvent<
      OkxRouterUpdatedEvent.InputTuple,
      OkxRouterUpdatedEvent.OutputTuple,
      OkxRouterUpdatedEvent.OutputObject
    >;

    "RebalanceExecuted(uint256,bytes32,address[],address[],uint256[],uint256[])": TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;
    RebalanceExecuted: TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;

    "RiskParamsUpdated()": TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;
    RiskParamsUpdated: TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
